In [1]:
import pandas as pd

In [2]:
# 讀入之前已經tokenzied完的資料
tokenStr_list = []
with open('il_news_token_all', 'r', encoding='utf-8') as f:
    for line in f.readlines():
        tokenStr_list.append(line)

In [3]:
# 重新回復到tokenize好的形狀
token_list = []
import re
#^0-9
def chuli(old_s):
    cop = re.compile("[^\u4e00-\u9fa5]")
    nwe_s = cop.sub("", old_s)
    return nwe_s
# remove redundant characters
for i in range(0, len(tokenStr_list)):
    tokenStr_list[i] = tokenStr_list[i].split(' ')
    token = str()
    for j in range(0, len(tokenStr_list[i])):
        if type(tokenStr_list[i][j]) == float:
            tokenStr_list[i][j] = ''
        tokenStr_list[i][j] = chuli(tokenStr_list[i][j])
        token += ' '
        token += tokenStr_list[i][j]
    token_list.append(token)

In [4]:
# import 文章資料
corp = pd.read_csv('il_news_all_2')

In [5]:
# 將需要的內容轉成list
id_text = corp['content'].values.tolist()
id_label = corp['label'].values.tolist()

In [12]:
# import libraries
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, mutual_info_classif
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import metrics

In [7]:
# import 中文stopwords
with open('stopwords_zh.txt', 'r', encoding='utf-8') as file:
    stopwords = file.read().splitlines() 
file.close()

# create TFIDF vectors

In [8]:
#建立TFIDF vectors
vectorizer = TfidfVectorizer(stop_words=stopwords)
X_train = vectorizer.fit_transform(token_list)
X_train = pd.DataFrame(X_train.toarray(),columns=vectorizer.get_feature_names_out())
X_train

C:\Users\jamie\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:396: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['lex', '①①', '①②', '①③', '①④', '①⑤', '①⑥', '①⑦', '①⑧', '①⑨', '①ａ', '①ｂ', '①ｃ', '①ｄ', '①ｅ', '①ｆ', '①ｇ', '①ｈ', '①ｉ', '①ｏ', '②①', '②②', '②③', '②④', '②⑤', '②⑥', '②⑦', '②⑧', '②⑩', '②ａ', '②ｂ', '②ｄ', '②ｅ', '②ｆ', '②ｇ', '②ｈ', '②ｉ', '②ｊ', '③①', '③⑩', '③ａ', '③ｂ', '③ｃ', '③ｄ', '③ｅ', '③ｆ', '③ｇ', '③ｈ', '④ａ', '④ｂ', '④ｃ', '④ｄ', '④ｅ', '⑤ａ', '⑤ｂ', '⑤ｄ', '⑤ｅ', '⑤ｆ', '１２', 'ｌｉ', 'ｚｘｆｉｔｌ'] not in stop_words.
  warnings.warn(

,一一一一年度,一一一億,一一一八一億,一一一年,一一一年度,一一九,一一九九七,一一二一二億,一一二年,一一六兆,...,龔神佑,龜尾,龜尾市,龜山,龜山區,龜山島,龜山廠,龜山水,龜裂,龜跑鱉
0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16438,0.0,0.0,0.0,0.0,0.369994,0.0,0.0,0.0,0.090299,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16439,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16440,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16441,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16442,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
# 將原始資料的漲跌設為真實值
y_train = id_label

In [10]:
# 選出表現較好的前1000個keywords，並藉此將TFIDF的維度降低
chi2_selector = SelectKBest(chi2, k = 10000)
chi2_selector.fit(X_train, y_train)
kbest_vocabs = X_train.columns[chi2_selector.get_support()]
X_train = X_train[kbest_vocabs]
X_train

,一一一年度,一一年度,一下子,一九年度,一二線,一共,一區,一半導體,一品,一哥,...,齊聲,齊買,齊跌,龍台,龍園,龍彩霖,龍潭,龍潭區,龔明德,龜山島
0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16438,0.369994,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16439,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16440,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16441,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16442,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Voting Method

In [13]:
SVM_rbf = SVC(kernel='rbf', C=1.0)
NB = BernoulliNB()
KNN_model = KNeighborsClassifier(n_neighbors = 5, weights='distance')

In [14]:
x_train, x_test, ytrain, ytest = train_test_split(X_train, y_train, test_size = 0.1)

In [15]:
SVM_rbf.fit(x_train, ytrain)
NB.fit(x_train, ytrain)
KNN_model.fit(x_train, ytrain)

KNeighborsClassifier(weights='distance')

In [16]:
#classify test data
predicted_results = []
expected_results = []

expected_results.extend(ytest)
rbf_pred = SVM_rbf.predict(x_test)
nb_pred = NB.predict(x_test)
knn_pred = KNN_model.predict(x_test)
for i in range(0, len(expected_results)):
    result = []
    result.append(rbf_pred[i])
    result.append(nb_pred[i])
    result.append(knn_pred[i])
    fell = 0
    rise = 0
    for j in range(3):
        if result[j] == '跌':
            fell += 1
        elif result[j] == '漲':
            rise += 1
    if fell >= 2:
        predicted_results.append('跌')
    elif rise >= 2:
        predicted_results.append('漲')

print(metrics.accuracy_score(expected_results, predicted_results))
print(metrics.confusion_matrix(expected_results, predicted_results, labels=['漲', '跌']))

0.7276595744680852
[[340 374]
 [ 74 857]]

In [ ]:
# 重複訓練模型，觀察模型平均效能
accu_rate = []
for k in range(20):
    x_train, x_test, ytrain, ytest = train_test_split(X_train, y_train, test_size = 0.1)
    SVM_rbf = SVC(kernel='rbf', C=1.0)
    NB = BernoulliNB()
    SVM_linear = SVC(kernel='linear', C=1.0)
    
    SVM_rbf.fit(x_train, ytrain)
    NB.fit(x_train, ytrain)
    SVM_linear.fit(x_train, ytrain)

    predicted_results = []
    expected_results = []

    expected_results.extend(ytest)
    rbf_pred = SVM_rbf.predict(x_test)
    nb_pred = NB.predict(x_test)
    linear_pred = SVM_linear.predict(x_test)
    for i in range(0, len(expected_results)):
        result = []
        result.append(rbf_pred[i])
        result.append(nb_pred[i])
        result.append(linear_pred[i])
        fell = 0
        same = 0
        rise = 0
        for j in range(3):
            if result[j] == '跌':
                fell += 1
            elif result[j] == '停':
                same += 1
            elif result[j] == '漲':
                rise += 1
        if fell >= 2:
            predicted_results.append('跌')
        elif same >= 2:
            predicted_results.append('停')
        elif rise >= 2:
            predicted_results.append('漲')
        elif (fell == 1 and same == 1) and rise == 1:
            predicted_results.append(rbf_pred[i])
    accu = metrics.accuracy_score(expected_results, predicted_results)
    accu_rate.append(accu)
    print(accu)

In [ ]:
print(sum(accu_rate)/20)